# -*- coding: utf-8 -*-
"""cameraon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13eMgukqGulKO6mh4N-Wn2yCXAIG1MrnD
"""

import tkinter as tk
from tkinter import messagebox
from ultralytics import YOLO
import cv2
from PIL import Image, ImageTk

# ---------------------------------------
# LOAD MODELS
# ---------------------------------------
models = {
    "Model-8": YOLO(r"D:\JU\yoloresult\result_model\best_yolo8.pt"),
    "Model-11": YOLO(r"D:\JU\yoloresult\result_model\best_yolo11.pt"),
    "Model-12": YOLO(r"D:\JU\yoloresult\result_model\best_yolo12.pt")
}

# Line Colors
model_colors = {
    "Model-8": (0, 255, 255),     # cyan
    "Model-11": (0, 128, 255),    # light blue
    "Model-12": (255, 128, 0)     # orange (contrast)
}

# ---------------------------------------
# DARK BLUE THEME COLORS
# ---------------------------------------
BG_MAIN = "#0d1b2a"        # dark navy
BG_FRAME = "#1b263b"       # medium-dark navy
BG_PANEL = "#1e2d45"       # side panel
FG_TEXT = "#e0e6ed"        # soft white/grey
FG_TITLE = "#4cc9f0"       # neon cyan
BTN_BG = "#415a77"
BTN_BG_ACTIVE = "#4cc9f0"
BTN_FG = "white"
BORDER_COLOR = "#4cc9f0"

# ---------------------------------------
# GUI WINDOW
# ---------------------------------------
root = tk.Tk()
root.title("YOLO Multi-Model Detection GUI - Dark Blue Tech")
root.geometry("1300x750")
root.configure(bg=BG_MAIN)

camera_running = False
cap = None

# ==========================================
# MAIN AREA
# ==========================================
main_frame = tk.Frame(root, bg=BG_MAIN)
main_frame.pack(pady=10)

# CAMERA FEED LEFT
video_label = tk.Label(main_frame, bg=BG_FRAME, bd=3, relief="solid",
                       highlightbackground=BORDER_COLOR,
                       highlightthickness=2)
video_label.grid(row=0, column=0, padx=20)

# COMPARISON PANEL (Initially Hidden)
compare_frame = tk.Frame(main_frame, bg=BG_PANEL, bd=2, relief="ridge",
                         highlightbackground=BORDER_COLOR, highlightthickness=2)

compare_title = tk.Label(
    compare_frame,
    text="Model Comparison",
    font=("Arial", 14, "bold"),
    fg=FG_TITLE,
    bg=BG_PANEL
)
compare_title.pack(pady=5)

compare_label = tk.Label(
    compare_frame,
    bg=BG_PANEL,
    fg=FG_TEXT,
    font=("Consolas", 12),
    justify="left",
    anchor="nw"
)
compare_label.pack(pady=10)

compare_frame.config(width=260, height=400)
compare_frame.pack_propagate(False)


# ==========================================
# CHECKBOXES (Dark Theme)
# ==========================================
checkbox_frame = tk.Frame(root, bg=BG_MAIN)
checkbox_frame.pack(pady=10)

style_checkbox = {
    "bg": BG_MAIN,
    "fg": FG_TEXT,
    "selectcolor": BG_PANEL,
    "font": ("Arial", 12)
}

var8 = tk.IntVar(value=1)
var11 = tk.IntVar(value=1)
var12 = tk.IntVar(value=1)

tk.Checkbutton(checkbox_frame, text="Enable Model-8", variable=var8, **style_checkbox)\
    .grid(row=0, column=0, padx=10)
tk.Checkbutton(checkbox_frame, text="Enable Model-11", variable=var11, **style_checkbox)\
    .grid(row=0, column=1, padx=10)
tk.Checkbutton(checkbox_frame, text="Enable Model-12", variable=var12, **style_checkbox)\
    .grid(row=0, column=2, padx=10)


# ==========================================
# START CAMERA
# ==========================================
def start_camera():
    global camera_running, cap
    if camera_running:
        return

    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        messagebox.showerror("Error", "Unable to open camera")
        return

    camera_running = True

    # SHOW Comparison Panel
    compare_frame.grid(row=0, column=1, padx=20)

    update_frame()


# ==========================================
# STOP CAMERA
# ==========================================
def stop_camera():
    global camera_running, cap
    camera_running = False

    if cap:
        cap.release()

    video_label.config(image="")
    compare_label.config(text="")
    compare_frame.grid_forget()  # Hide comparison box


# ==========================================
# MAIN LOOP FOR CAMERA
# ==========================================
def update_frame():
    global camera_running, cap

    if not camera_running:
        return

    ret, frame = cap.read()
    if not ret:
        stop_camera()
        return

    summary_text = ""

    # --- MODEL 8 ---
    if var8.get() == 1:
        results = models["Model-8"](frame, stream=True)
        for r in results:
            for box in r.boxes:
                x1,y1,x2,y2 = box.xyxy[0].cpu().numpy().astype(int)
                conf = float(box.conf[0])
                cls = models["Model-8"].names[int(box.cls[0])]
                color = model_colors["Model-8"]
                cv2.rectangle(frame, (x1,y1), (x2,y2), color, 2)
                cv2.putText(frame, f"8:{cls} {conf:.2f}", (x1, y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2)
                summary_text += f"Model-8 → {cls} ({conf:.2f})\n"

    # --- MODEL 11 ---
    if var11.get() == 1:
        results = models["Model-11"](frame, stream=True)
        for r in results:
            for box in r.boxes:
                x1,y1,x2,y2 = box.xyxy[0].cpu().numpy().astype(int)
                conf = float(box.conf[0])
                cls = models["Model-11"].names[int(box.cls[0])]
                color = model_colors["Model-11"]
                cv2.rectangle(frame, (x1,y1), (x2,y2), color, 2)
                cv2.putText(frame, f"11:{cls} {conf:.2f}", (x1, y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2)
                summary_text += f"Model-11 → {cls} ({conf:.2f})\n"

    # --- MODEL 12 ---
    if var12.get() == 1:
        results = models["Model-12"](frame, stream=True)
        for r in results:
            for box in r.boxes:
                x1,y1,x2,y2 = box.xyxy[0].cpu().numpy().astype(int)
                conf = float(box.conf[0])
                cls = models["Model-12"].names[int(box.cls[0])]
                color = model_colors["Model-12"]
                cv2.rectangle(frame, (x1,y1), (x2,y2), color, 2)
                cv2.putText(frame, f"12:{cls} {conf:.2f}",
                            (x1, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2)
                summary_text += f"Model-12 → {cls} ({conf:.2f})\n"

    compare_label.config(text=summary_text)

    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    img = ImageTk.PhotoImage(Image.fromarray(rgb))
    video_label.imgtk = img
    video_label.config(image=img)

    video_label.after(10, update_frame)


# ==========================================
# BUTTONS
# ==========================================
button_frame = tk.Frame(root, bg=BG_MAIN)
button_frame.pack(pady=20)

btn_style = {
    "font": ("Arial", 14),
    "bg": BTN_BG,
    "fg": BTN_FG,
    "activebackground": BTN_BG_ACTIVE,
    "activeforeground": "black",
    "width": 15
}

tk.Button(button_frame, text="Start Camera", command=start_camera, **btn_style)\
    .grid(row=0, column=0, padx=20)

tk.Button(button_frame, text="Stop Camera (a)", command=stop_camera, **btn_style)\
    .grid(row=0, column=1, padx=20)


# Keyboard Shortcut.............................................
def key_handler(event):
    if event.char == "a":
        stop_camera()

root.bind("<Key>", key_handler)


root.mainloop()

