# -*- coding: utf-8 -*-
"""CameraandVideoyolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10z_tkq4oqZIayAgGyy65T9Mv1Xx38CGg
"""

import tkinter as tk
from tkinter import messagebox, filedialog
from ultralytics import YOLO
import cv2
from PIL import Image, ImageTk
import numpy as np
import time

# ---------------------------------------
# LOAD MODELS
# ---------------------------------------
models = {
    "Model-8": YOLO(r"D:\JU\yoloresult\result_model\best_yolo8.pt"),
    "Model-11": YOLO(r"D:\JU\yoloresult\result_model\best_yolo11.pt"),
    "Model-12": YOLO(r"D:\JU\yoloresult\result_model\best_yolo12.pt")
}

model_colors = {
    "Model-8": (179, 230, 255),
    "Model-11": (0, 128, 255),
    "Model-12": (255, 128, 0)
}

# ---------------------------------------
# THEME COLORS
# ---------------------------------------
BG_MAIN = "#0d1b2a"
BG_FRAME = "#1b263b"
FG_TEXT = "#e0e6ed"

# ---------------------------------------
# GUI SETUP
# ---------------------------------------
root = tk.Tk()
root.title("YOLO Multi-Model Camera & Video Dashboard")
root.geometry("1300x800")
root.configure(bg=BG_MAIN)

camera_running = False
video_running = False
cap = None

# ---------------------------------------
# Store model confidence and class distribution
# ---------------------------------------
model_confidences = {"Model-8": [], "Model-11": [], "Model-12": []}
MAX_HISTORY = 50

# FPS
prev_time = time.time()
fps = 0

# ==========================================
# MAIN FRAME
# ==========================================
main_frame = tk.Frame(root, bg=BG_MAIN)
main_frame.pack(pady=10)

video_label = tk.Label(main_frame, bg=BG_FRAME, bd=3, relief="solid")
video_label.pack()

# ==========================================
# CHECKBOXES
# ==========================================
checkbox_frame = tk.Frame(root, bg=BG_MAIN)
checkbox_frame.pack(pady=10)

style_checkbox = {"bg": BG_MAIN, "fg": FG_TEXT, "selectcolor": BG_FRAME, "font": ("Arial", 12)}
var8 = tk.IntVar(value=1)
var11 = tk.IntVar(value=1)
var12 = tk.IntVar(value=1)

tk.Checkbutton(checkbox_frame, text="Enable Model-8", variable=var8, **style_checkbox).grid(row=0, column=0, padx=10)
tk.Checkbutton(checkbox_frame, text="Enable Model-11", variable=var11, **style_checkbox).grid(row=0, column=1, padx=10)
tk.Checkbutton(checkbox_frame, text="Enable Model-12", variable=var12, **style_checkbox).grid(row=0, column=2, padx=10)

# ==========================================
# CAMERA / VIDEO SETTINGS
# ==========================================
CAM_WIDTH, CAM_HEIGHT = 900, 550

# ==========================================
# DRAW HORIZONTAL BAR
# ==========================================
def draw_horizontal_bar(frame, start_x, start_y, width, height, value, max_value, color, label=""):
    cv2.rectangle(frame, (start_x, start_y), (start_x + width, start_y + height), (50,50,50), -1)
    fill_width = int((value / max_value) * width)
    cv2.rectangle(frame, (start_x, start_y), (start_x + fill_width, start_y + height), color, -1)
    cv2.putText(frame, f"{label} {value:.1f}%", (start_x + 5, start_y + height - 3),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,255,255), 1)

# ==========================================
# UPDATE FRAME (CAMERA OR VIDEO)
# ==========================================
def update_frame():
    global camera_running, video_running, cap, prev_time, fps, model_confidences
    if not camera_running and not video_running:
        return

    ret, frame = cap.read()
    if not ret:
        stop_all()
        return

    # Resize frame
    frame = cv2.resize(frame, (CAM_WIDTH, CAM_HEIGHT))

    # FPS calculation
    curr_time = time.time()
    fps = 1 / (curr_time - prev_time)
    prev_time = curr_time
    cv2.putText(frame, f"FPS: {fps:.1f}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,255,0), 2)

    # Reset class counts for frame
    class_counts_frame = {}

    # Process models
    enabled_models = {"Model-8": var8.get(), "Model-11": var11.get(), "Model-12": var12.get()}
    y_offset = 50
    bar_width = 180
    bar_height = 20
    gap = 10

    for model_name, enabled in enabled_models.items():
        if enabled == 1:
            results = models[model_name](frame, stream=True)
            avg_conf = 0
            count = 0
            for r in results:
                for box in r.boxes:
                    x1,y1,x2,y2 = box.xyxy[0].cpu().numpy().astype(int)
                    conf = float(box.conf[0])
                    cls = models[model_name].names[int(box.cls[0])]
                    color = model_colors[model_name]
                    cv2.rectangle(frame, (x1,y1), (x2,y2), color, 2)
                    cv2.putText(frame, f"{model_name[-2:]}:{cls} {conf:.2f}", (x1, y1-10),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2)
                    avg_conf += conf
                    count += 1
                    class_counts_frame[cls] = class_counts_frame.get(cls, 0) + 1

            # Update model confidence history
            confidence_percent = (avg_conf / count)*100 if count > 0 else 0
            model_confidences[model_name].append(confidence_percent)
            if len(model_confidences[model_name]) > MAX_HISTORY:
                model_confidences[model_name].pop(0)

            # Draw model confidence bars
            start_x = CAM_WIDTH - 200
            draw_horizontal_bar(frame, start_x, y_offset, bar_width, bar_height,
                                np.mean(model_confidences[model_name]), 100,
                                model_colors[model_name], label=model_name)
            y_offset += bar_height + gap

    # Draw class distribution bars under model bars
    class_y_offset = y_offset + 20
    for cls, val in class_counts_frame.items():
        color = (200,150,50)
        draw_horizontal_bar(frame, CAM_WIDTH - 200, class_y_offset, bar_width, bar_height,
                            min(val, MAX_HISTORY*2), MAX_HISTORY*2, color, label=cls)
        class_y_offset += bar_height + gap

    # Display frame
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    img = ImageTk.PhotoImage(Image.fromarray(rgb))
    video_label.imgtk = img
    video_label.config(image=img)

    video_label.after(10, update_frame)

# ==========================================
# BUTTONS
# ==========================================
def start_camera():
    global camera_running, video_running, cap
    stop_all()
    camera_running = True
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        messagebox.showerror("Error", "Unable to open camera")
        return
    update_frame()

def upload_video():
    global video_running, camera_running, cap
    stop_all()
    file_path = filedialog.askopenfilename(title="Select Video", filetypes=[("Video files","*.mp4 *.avi")])
    if not file_path:
        return
    cap = cv2.VideoCapture(file_path)
    if not cap.isOpened():
        messagebox.showerror("Error", "Cannot open video file")
        return
    video_running = True
    update_frame()

def stop_all():
    global camera_running, video_running, cap
    camera_running = False
    video_running = False
    if cap:
        cap.release()
    video_label.config(image="")

button_frame = tk.Frame(root, bg=BG_MAIN)
button_frame.pack(pady=10)

btn_style = {"font": ("Arial", 14), "bg": "#415a77", "fg": "white",
             "activebackground": "#4cc9f0", "activeforeground": "black", "width": 15}

tk.Button(button_frame, text="Start Camera", command=start_camera, **btn_style).grid(row=0, column=0, padx=10)
tk.Button(button_frame, text="Upload Video", command=upload_video, **btn_style).grid(row=0, column=1, padx=10)
tk.Button(button_frame, text="Stop (a)", command=stop_all, **btn_style).grid(row=0, column=2, padx=10)

# Keyboard shortcut
def key_handler(event):
    if event.char == "a":
        stop_all()
root.bind("<Key>", key_handler)

root.mainloop()

